### ISSUE TITLE
missing parameters ?

### ISSUE THREAD

**Issue by raymerjacque** [yihong0618/IdeoImageCreator#2]
```
from ideo import ImageGen
i = ImageGen('cookie', 'user_id', 'auth_token') # Replace 'cookie', 'user_id', and 'auth_token' with your own values
print(i.get_limit_left())
i.save_images("a blue cyber dream", './output')
```

################

why do you ONLY allow for user input parameter ?  what about aspect ratio ? what about generation speed ? what about style ? what about variation strength ? 

you have hard coded these values and as such the user cannot use them to connect to "pip install -U ideo".

Please fix it so that users can send those parameters optional and if they aren't present, ONLY then it uses the default ones.

**Comment by yihong0618** [comment]
no I do not want to do that for simple use, if you want you can fork the repo or change it by yourself.
It's very rude to make demands like that. I don't owe you anything.

**Comment by laike9m** [comment]
@raymerjacque what else can you do besides creating bullshit in different repos, huh?

**Comment by QinRay** [comment]
Here is an open-source platform, you can contribute by submitting pull requests or just forking the repository to freely work on your own ideas. However, it's important to remember not to impose ORDERS on others. Asking questions is a sign of wisdom.

**Comment by jfarre20** [comment]
I honestly used Claude 2 at claude.ai to modify this for aspect and stuff. Works great but the code is nasty and not worth a PR.
